package io.github.kingg22.godot.binding

import io.github.kingg22.godot.api.builtin.asStringName
import io.github.kingg22.godot.api.core.GodotObject
import io.github.kingg22.godot.api.singleton.ClassDB
import io.github.kingg22.godot.internal.binding.BindingProcAddressHolder
import io.github.kingg22.godot.internal.binding.InternalBinding
import io.github.kingg22.godot.internal.binding.ObjectBinding
import io.github.kingg22.godot.internal.binding.getInstance
import io.github.kingg22.godot.internal.ffi.GDExtensionClassInstancePtr
import io.github.kingg22.godot.internal.ffi.GDExtensionInstanceBindingCallbacks
import io.github.kingg22.godot.internal.ffi.GDExtensionObjectPtr
import kotlinx.cinterop.cValue
import kotlinx.cinterop.memScoped

// Tienes que usar la función de GDExtension para obtener el binding
@InternalBinding
public fun getInstanceBinding(objectPtr: GDExtensionObjectPtr): GDExtensionClassInstancePtr? = memScoped {
    ObjectBinding.instance.getInstanceBindingRaw(
        pO = objectPtr,
        pToken = BindingProcAddressHolder.library,
        pCallbacks = cValue<GDExtensionInstanceBindingCallbacks> {
            create_callback = null
            free_callback = null
            reference_callback = null
        }.ptr,
    )
}

/**
 * Instantiate a Godot object of type [T].
 *
 * ```kotlin
 * @Godot class MyGodotClass(rawPtr: ObjectPtr) : Node(rawPtr)
 *
 * val myObject: MyGodotClass = instantiate()
 * ```
 *
 * **For API classes**: use the secondary constructor, the godot name should not be the same as the Kotlin class name.
 * This method will fail due to missing the kotlin instance.
 *
 * **For custom classes**: prefers the top-level factory function generated by the Kogot processor, this is a fallback.
 *
 * **Safety**: The class must not be anonymous and requires already registered in the ClassDB with Godot.
 *
 * **Note**: The following code is **invalid**, DON'T do that:
 *
 * ```kotlin
 * val myObject: MyGodotClass = MyGodotClass(Node().rawPtr) // This is invalid
 * val myNode: Node = instantiate() // This will fail
 * ```
 */
public inline fun <reified T : GodotObject> instantiate(): T {
    val nativePtr = requireNotNull(T::class.simpleName) {
        "Cannot instantiate ${T::class.qualifiedName} without a valid class name"
    }.asStringName().use { str ->
        ClassDB.instance.instantiate(str)
    }.asObject().rawPtr

    // Ahora sí, ese bindingPtr es el `selfPtr` (StableRef) que guardamos antes.
    @OptIn(InternalBinding::class)
    return getInstanceBinding(nativePtr).getInstance()
}
