package io.github.kingg22.godot.binding

import io.github.kingg22.godot.api.builtin.asStringName
import io.github.kingg22.godot.api.core.GodotObject
import io.github.kingg22.godot.api.singleton.ClassDB
import kotlinx.cinterop.COpaquePointer

/**
 * Instantiate a Godot object of type [T] using the given [constructor] must be the constructor.
 *
 * ```kotlin
 * @Godot class MyGodotClass(rawPtr: ObjectPtr) : Node(rawPtr)
 *
 * val myObject: MyGodotClass = instantiate(::MyGodotClass)
 * ```
 *
 * **For API classes**: use the secondary constructor, the godot name should not be the same as the Kotlin class name.
 *
 * **For custom classes**: prefers the top-level factory function generated by the Kogot processor, this is a fallback.
 *
 * **Safety**: The class must not be anonymous and requires already registered in the ClassDB with Godot.
 *
 * **Note**: The following code is **invalid**, DON'T do that:
 *
 * ```kotlin
 * val myObject: MyGodotClass = MyGodotClass(Node().rawPtr)
 * ```
 */
public inline fun <reified T : GodotObject> instantiate(constructor: (nativePtr: COpaquePointer) -> T): T {
    val nativePtr = requireNotNull(T::class.simpleName) {
        "Cannot instantiate ${T::class.qualifiedName} without a valid class name"
    }.asStringName().use { str ->
        ClassDB.instance.instantiate(str)
    }.asObject().rawPtr

    return constructor(nativePtr)
}
