package io.github.kingg22.godot.binding

import io.github.kingg22.godot.api.builtin.toStringName
import io.github.kingg22.godot.api.core.GodotObject
import io.github.kingg22.godot.api.singleton.ClassDB
import io.github.kingg22.godot.internal.binding.InternalBinding
import io.github.kingg22.godot.internal.binding.resolveBinding

/**
 * Instantiate a Godot object of type [T].
 *
 * ```kotlin
 * @Godot class MyGodotClass(rawPtr: ObjectPtr) : Node(rawPtr)
 *
 * val myObject: MyGodotClass = instantiate()
 * ```
 *
 * **For API classes**: use the secondary constructor, the godot name should not be the same as the Kotlin class name.
 * This method will fail due to missing the kotlin instance.
 *
 * **For custom classes**: prefers the top-level factory function generated by the Kogot processor, this is a fallback.
 *
 * **Safety**: The class must not be anonymous and requires already registered in the ClassDB with Godot.
 *
 * **Note**: The following code is **invalid**, DON'T do that:
 *
 * ```kotlin
 * val myObject: MyGodotClass = MyGodotClass(Node().rawPtr) // This is invalid
 * val myNode: Node = instantiate() // This will fail
 * ```
 */
public inline fun <reified T : GodotObject> instantiate(): T {
    val nativePtr = requireNotNull(T::class.simpleName) {
        "Cannot instantiate ${T::class.qualifiedName} without a valid class name"
    }.toStringName().use { str ->
        ClassDB.instance.instantiate(str)
    }.toObject().rawPtr

    // create_instance_func (registerClass) already materialized and cached the Kotlin instance for
    // nativePtr — resolve it back instead of building a second one (issue #114).
    @OptIn(InternalBinding::class)
    return requireNotNull(resolveBinding<T>(nativePtr)) {
        "No Kotlin instance bound for a freshly-instantiated '${T::class.simpleName}' ($nativePtr) — " +
            "was it registered via createInstanceFunc?"
    }
}
