/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin.
    // Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)
    implementation("com.diffplug.spotless:spotless-plugin-gradle:8.2.1")
    implementation("net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:5.0.0")
    implementation("net.ltgt.nullaway:net.ltgt.nullaway.gradle.plugin:3.0.0")
    implementation(libs.asm)
}
