package io.github.kingg22.kogot.processor.generation.kotlin

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec

fun FileSpec.Builder.applyCommonConfig(): FileSpec.Builder = apply {
    indent("    ")
    addFileComment("Generated by the Kogot KSP Processor. DO NOT EDIT!")

    addAnnotation(
        AnnotationSpec.builder(K_SUPPRESS)
            .addMember("%S", "ktlint")
            .addMember("%S", "detekt:all")
            .addMember("%S", "ClassName")
            .addMember("%S", "EnumEntryName")
            .addMember("%S", "FunctionName")
            .addMember("%S", "LocalVariableName")
            .addMember("%S", "RemoveRedundantQualifierName")
            .addMember("%S", "REDUNDANT_VISIBILITY_MODIFIER")
            .addMember("%S", "SpellCheckingInspection")
            .addMember("%S", "GrazieInspection")
            .addMember("%S", "GrazieStyle")
            .addMember("%S", "NOTHING_TO_INLINE")
            .build(),
    )
}

fun FileSpec.Builder.optInInternalBindingAndForeignNative() = apply {
    addAnnotation(
        AnnotationSpec.builder(K_OPT_IN)
            .addMember("%T::class", InternalBindingClassName)
            .addMember("%T::class", ExperimentalForeignApi)
            .build(),
    )
}
