package io.github.kingg22.godot.codegen.impl

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import io.github.kingg22.godot.codegen.types.K_SUPPRESS

fun createFile(
    type: TypeSpec,
    fileName: String,
    packageName: String,
    block: FileSpec.Builder.() -> Unit = {},
): FileSpec = FileSpec
    .builder(packageName, fileName)
    .commonConfiguration()
    .addType(type)
    .apply(block)
    .build()

fun createFile(fileName: String, packageName: String, block: FileSpec.Builder.() -> Unit): FileSpec = FileSpec
    .builder(packageName, fileName)
    .commonConfiguration()
    .apply(block)
    .build()

fun FileSpec.Builder.commonConfiguration() = apply {
    indent("    ") // use 4 spaces https://pinterest.github.io/ktlint/latest/rules/standard/#indentation
    addFileComment("Generated by the Kogot Code Generator. DO NOT EDIT!")
    addAnnotation(
        AnnotationSpec
            .builder(K_SUPPRESS)
            .addMember("%S", "ktlint")
            .addMember("%S", "detekt:all")
            .addMember("%S", "ClassName")
            .addMember("%S", "EnumEntryName")
            .addMember("%S", "FunctionName")
            .addMember("%S", "LocalVariableName")
            .addMember("%S", "RemoveRedundantQualifierName")
            .addMember("%S", "REDUNDANT_VISIBILITY_MODIFIER")
            .addMember("%S", "SpellCheckingInspection")
            .addMember("%S", "GrazieInspection")
            .addMember("%S", "GrazieStyle")
            .addMember("%S", "NOTHING_TO_INLINE")
            .build(),
    )
}
